### ISSUE TITLE
issue with creating a new project on Visual Studio Code

### ISSUE THREAD

**Issue by iatebreakfasttoday** [decentraland/editor-sdk7#46]
Hi, I've been following the instructions provided on https://docs.decentraland.org/creator/development-guide/sdk7/sdk-101/  I wanted to create a new project, I chose an empty folder etc. but once I click to create a new project, it goes on but suddenly stops installing dependencies. I'm attaching a screenshot below. Could you tell me what Im doing wrong? I'm not a software developer, so I'm sorry in advance if this is obvious.
![Przechwytywanie](https://github.com/decentraland/editor-sdk7/assets/137005717/ae1c2782-8507-47b9-abcc-3fc25b891064)

**Comment by iatebreakfasttoday** [comment]
also I can't really choose a type of project (scene with rotating cube etc.) while creating a new project
![fd](https://github.com/decentraland/editor-sdk7/assets/137005717/f7888066-328a-4373-a08e-a8355af43ce9)

**Comment by aminekha** [comment]
I'm having the same issue on MacOS

**Comment by nicoecheza** [comment]
just released version `1.15.1` of the extension, can you update it and try on a fresh new scene?

> also I can't really choose a type of project (scene with rotating cube etc.) while creating a new project ![fd](https://user-images.githubusercontent.com/137005717/246691449-f7888066-328a-4373-a08e-a8355af43ce9.JPG)

we will be adding more templates in the future, but for now we are only providing the basic scene template

**Comment by iatebreakfasttoday** [comment]
Hey Nicolas, thank you for releasing an updated version - I managed to run
the scene finally, no problems with the server etc.
But I'm encountering another problem - as I try to import the avocado glb
model I'm running into this issue with the code as on the screen below:
[image: image.png]
it cannot find those names (gltfcontainer etc.) is it because it's not gltf
format but glb?
Maybe I put those code lines in the wrong place? I tried to follow these
instructions provided in docs :
[image: image.png]

Again, thank you for releasing the update! I will appreciate your help with
this issue above

Nadia.

**Comment by iatebreakfasttoday** [comment]
Hey Nicolas, thank you for releasing an updated version - I managed to run the scene finally, no problems with the server etc.
But I'm encountering another problem - as I try to import the avocado glb model I'm running into this issue with the code as on the screen below:
![image](https://github.com/decentraland/editor-sdk7/assets/137005717/7d3a6744-c06c-4d9a-9a59-d59166a9f5e7)
it cannot find those names (gltfcontainer etc.) is it because it's not gltf format but glb?
Maybe I put those code lines in the wrong place? I tried to follow these instructions provided in docs :
![image (8)](https://github.com/decentraland/editor-sdk7/assets/137005717/3f392b60-f651-475c-b83d-c505933e1a6e)
Again, thank you for releasing the update! I will appreciate your help with this issue above

**Comment by nicoecheza** [comment]
glad to hear the preview is now running.

about the errors you are getting in your scene file:
1. You need to import `GltfContainer` and `Transform` components from `'@dcl/sdk/ecs'`
2. You need to import `Vector3` from `'@dcl/sdk/math'`

it should work fine after those changes 👌

**Comment by iatebreakfasttoday** [comment]
Thank you Nicolas, one more question - I'm trying to import Vector3, by writing accordingly in the terminal of sdk but I'm facing errors:
![image](https://github.com/decentraland/editor-sdk7/assets/137005717/1a9bd0cd-7c4d-4f58-a77a-e9eb72e623eb)

could you tell me what I'm doing wrong?

**Comment by nicoecheza** [comment]
@iatebreakfasttoday I've closed this issue since the main problem was solved, but you can ask any development-related question in our discord: https://dcl.gg/discord. Just join the `sdk` channel and people there will be willing to help 👌 👌
