### ISSUE TITLE
Incorrect Link SDK7 -> Decentraland Editor Page

### ISSUE THREAD

**Issue by awedjob** [decentraland/editor-sdk7#48]
The ["Reporting an Issue" section of the "Decentraland Editor" page](https://docs.decentraland.org/creator/development-guide/sdk7/editor/#reporting-issues) in the SDK7 docs states:
"Reporting issues #
If you run into any bugs, please report an issue in the Editor repository.

We ask you to please detail how to reproduce the issue as much as possible."

The link for the SDK7 Editor Repository takes me here:
https://github.com/decentraland/editor-sdk6

It instead should link to this page:
https://github.com/decentraland/editor-sdk7

**Comment by nearnshaw** [comment]
Thanks for reporting
I just updated this in the docs!
